sudo: required
dist: trusty
language: python

matrix:
    include:
        - python: 3.6

install:
  - pip install -e .[tests]
  - pip install tensorflow==2.0.0-alpha0
  
script:
  - PYTHONPATH=$PWD:$PYTHONPATH py.test tests/
