sudo: required
dist: trusty
language: python

matrix:
    include:
        - python: 3.6
          env: EYWA_MATH_BACKEND=numpy
        - python: 3.6:
          env: EYWA_MATH_BACKEND=numba

install:
  - pip install -e .[tests]

script:
  - py.test
