site_name:  Eywa - Framework for Conversational Agents
theme:
  name: null
  custom_dir: theme
  static_templates:
    - 404.html
  include_search_page: true
  search_index_only: false
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false

docs_dir: sources
repo_url: https://github.com/abhijithneilabraham/eywa/tree/master/eywa
site_url: https://abhijithneilabraham.github.io/eywabot/
site_description: 'Documentation for Eywa,the Conversational AI'
nav:
    - Eywa - Framework for Conversational Agents: index.md
    - Models:
             Classifier: models/Classifer.md
             EntityExtractor: models/EntityExtractor.md
